# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac7a674a0987ec9ad08dc15bc58c7da3fed4482d98c0ef0c25d3f93a72b950fc4bc9a52f01cfaffb578602b05fc3ac8c3c0c315e3969c1473da1799b775d2cc0

test:
  secret_key_base: e9b1ab405a365f281a7785bafd5fa3fcb7913305d9d4d8db76bb3bb4a83ee62b16ab2fd9192baf0f0de00282ec71b46c215db8452031176628ad2e1f628367f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
